# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: deploy maven snapshot jar to packages

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: init mysql
        run: |
          sudo /etc/init.d/mysql start
          export MYSQL_PWD=root
          for i in *.sql;do echo $i;mysql -h localhost -uroot < $i;done
        working-directory: support-files/sql
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Build
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 4.8.1
          build-root-directory: src/backend/ci
          arguments: test uploadArchives -DmavenRepoUsername=${{ github.actor }} -DmavenRepoPassword=${{ secrets.GITHUB_TOKEN }} -DmavenRepoUrl="http://maven.aliyun.com/nexus/content/groups/public/" -DmavenRepoDeployUrl="https://maven.pkg.github.com/Tencent/bk-ci"
